### PR TITLE
Fix #150: better styling

### LINKED ISSUE #150: [searchkit] better styling for the "expanded details"
See point 5 in https://github.com/mozilla-services/buildhub/pull/135#issuecomment-308193225

### PR DESCRIPTION
**Pull request by magopian**
Fixes #150

This is a second attempt to improve the styling. It's really not my strong point, so please let me know what you think @n1k0 

screenshot from 2017-06-15 14-56-21

I tried sticking as closely as possible to the styling in the elm version, but with the colors from searchkit.

### CODE REVIEW

**Comment by n1k0** [comment]
Much better, yet I'm finding the build details a little messy:



How about having the different sections as distinct columns instead stacking up these tables?

**Comment by magopian** [comment]
I'm not sure I understand what you mean, are you talking about having a single table, and then each section (target, download, build...) being a column, and then in those columns you would have one info per line?

**Comment by n1k0** [comment]
yes

**Comment by magopian** [comment]
Gave it a try, but it seems a bit crowded:

screenshot from 2017-06-15 16-45-06

How could we improve that @n1k0 ?

**Comment by n1k0** [comment]
25% width columns?

**Comment by magopian** [comment]
Sure we can even up the columns, but it's still a lot of information to cram into a small horizontal space, don't you think?

screenshot from 2017-06-15 17-09-56

And obviously feel free to take over, you're way better at design ;)

**Comment by n1k0** [comment]
I went with this, thoughts?

**Comment by mostlygeek** [comment]
The column based approach is very nice. 

There's quite a bit of duplicated information. My suggestions: 

searchkit-tweaks

1. The `Target` column can be squashed into the title.
    * `fennec 56.0a1 (android-arm | nightly | Locale: it)` 
1. The `Build` column is totally redundant 
1. The Build id and revision can also squashed to the title bar: `20170614100332 (b266a8)` 
    * a truncated hash conveys as much info as a full length one for humans... 
1. The mimetype doesn't tell us anything the file extension in the URL doesn't. 
1. Size can be made more human readable, ie: 36MB vs 36137120

**Comment by magopian** [comment]
Good ideas and suggestions, will implement. One catch though: the published date and the build date aren't exactly the same. Should we keep only one of the two? Or maybe change the title one to be the build date (when present), and keep the published date in the "download" section?

**Comment by n1k0** [comment]
I tend to concur that all these information could probably fit as columns in a regular table row.

**Comment by magopian** [comment]
Another try:

screenshot from 2017-06-16 10-24-22

**Comment by n1k0** [comment]
I still feel like everything could actually fit on a single row, with no need to expand. That depends if we plan to add more info in the future or not though.

**Comment by magopian** [comment]
I'll open a new PR using the original layout/styling, and adding more information (without the "expand" feature).

**Comment by magopian** [comment]
Closing this in favor of #164

**Pull request closed without merging**
