### PR TITLE
Another attempt at improving the styling for #150

### LINKED ISSUE #150: [searchkit] better styling for the "expanded details"
See point 5 in https://github.com/mozilla-services/buildhub/pull/135#issuecomment-308193225

### PR DESCRIPTION
**Pull request by magopian**
Fixes #150

screenshot from 2017-06-16 11-12-00

### CODE REVIEW

**Comment by magopian** [comment]
Thanks for the feedback:

screenshot from 2017-06-16 11-28-34

Thoughts @n1k0 ?

**Comment by magopian** [comment]
Maybe we'd want to also have its own column for the version...

**Comment by n1k0** [comment]
Starts looking really nice. Classic stuff, but well known by users and immediately useful when seeking for a specific info.

> Maybe we'd want to also have its own column for the version...

If we plan on allowing ordering that column eventually, yes.

**Comment by magopian** [comment]
Should we merge this one and close #161 then?

**Comment by n1k0** [comment]
A few ideas to gain some real estate:

- Could we find a shoter date format?
- We could put the build id in the first or second column and remove the `#` link
- This may sound silly but if we could find the three icons for ffx, fennec and tb, we could avoid displaying the product name :D

**Comment by n1k0** [comment]
> Should we merge this one and close #161 then?

Ah sorry you commented while I was writing my previous comment. Up to you, we can always iterate further in other PRs.

**Comment by magopian** [comment]
Regarding the `#` it's the permalink to get back to the specific row. The link on the build id is the link to the revision in the repository. I think we want to keep the permalink somehow.

**Comment by n1k0** [comment]
Ah right indeed.

**Comment by magopian** [comment]
Going to land this now.

**Pull request merged**
