### PR TITLE
Fix #89: Update filters so they act like a form.

### LINKED ISSUE #89: Debounce the build id search box
At the moment, a request is sent to Kinto on each keypress. We should rather debounce it (only send a request whenever no keypress was detected for 200ms or more, or add a "search" button).

### PR DESCRIPTION
**Pull request by n1k0**
Fixes #89. This patch wraps current filters into a form you submit as a whole everytime you want to refine your current search.

### Pros

- It saves a bunch of http requests
- It reallows filtering build ids along other filters

### Cons 

- Usage is a little less *dynamic* as you need to submit the form to run a search.

Thoughts?

### CODE REVIEW

**Comment by n1k0** [comment]
Patch has been merged with latest master (error handling) and deployed to production for easier QA.

**Comment by n1k0** [comment]
Ok I'm just realizing that this approach isn't gonna work when we move to facetted search, where we'll have to update filter lists according to results everytime we refine them.

I'm not closing the PR for now as this might serve as a temporary demo.

**Comment by magopian** [comment]
We can have the search on build id "among" the other filters without having to transform the filters as a form. I just didn't think searching for a build id at the same time as other filters was a valid use case, if it is, i'm fine with it.

Regarding transforming the filters as a form, i believe this discussion should be linked with the issue #48. The idea there was to have some "pre filters" that we would force the user to choose before the first list is being displayed.

I'l still not sure how much sense that makes:
1/ not sure it's easier/more ergonomic
2/ not sure it's needed (we don't have that many records, less than 40k, and the current application seems very snappy, at least to me)

**Comment by n1k0** [comment]
I think the key idea behind faceted search is discovery. You start picking a first filter, then another one, and the result list updates accordingly along a refined filter list. That's super convenient when browsing Amazon, but Firefox builds? Honestly, I dunno.

**Comment by magopian** [comment]
Let's land this, and we'll see about faceted search later.

**Pull request merged**
