### PR TITLE
Wait for the server to have started before running kinto-wizard

### PR DESCRIPTION
**Pull request by peterbe**
Experimenting because I can't easily test this on my macbook.

### CODE REVIEW

**Comment by peterbe** [comment]
Perhaps this is easier https://gist.github.com/rgl/f90ff293d56dbb0a1e0f7e7e89a81f42

**Comment by leplatrem** [comment]
> Perhaps this is easier https://gist.github.com/rgl/f90ff293d56dbb0a1e0f7e7e89a81f42

There is even simpler:

`curl --retry 3 --retry-connrefused http://localhost:8888/v1/`

will retry until it succeeds :) 

So theorically `- curl --retry 3 --retry-connrefused http://localhost:8888/v1/ && kinto-wizard ...` should do it :)

**Comment by peterbe** [comment]
But does the curl thing sleep at all?

**Comment by leplatrem** [comment]
> But does the curl thing sleep at all?

Yes :) Exponentially by default (retry after 1, 2, 4, 8 seconds...)

```
$ curl --retry 3 --retry-connrefused http://localhost:8888/v1/ 
Warning: Transient problem: connection refused Will retry in 1 seconds. 3 
Warning: retries left.
Warning: Transient problem: connection refused Will retry in 2 seconds. 2 
Warning: retries left.
Warning: Transient problem: connection refused Will retry in 4 seconds. 1 
Warning: retries left.
curl: (7) Failed to connect to localhost port 8888: Connection refused

$ echo $?
7
```

Starting kinto in the mean time:
```
$ curl --retry 3 --retry-connrefused http://localhost:8888/v1/
Warning: Transient problem: connection refused Will retry in 1 seconds. 3 
Warning: retries left.
Warning: Transient problem: connection refused Will retry in 2 seconds. 2 
Warning: retries left.
{"project_name":"kinto","project_version":"8.1.5.dev0","http_api_version":"1.18","project_docs":"https://kinto.readthedocs.io/","url":"http://localhost:8888/v1/","settings":{"readonly":false,"batch_max_requests":25},"capabilities":{"basicauth":{"description":"Very basic authentication sessions. Not for production use.","url":"http://kinto.readthedocs.io/en/stable/api/1.x/authentication.html"},"default_bucket":{"description":"The default bucket is an alias for a personal bucket where collections are created implicitly.","url":"https://kinto.readthedocs.io/en/latest/api/1.x/buckets.html#personal-bucket-default"}}}%  

$ echo $?
0
```

**Comment by peterbe** [comment]
PR updated.

**Comment by peterbe** [comment]
@leplatrem that didn't work :) ANy idea?

**Comment by leplatrem** [comment]
```
curl: option --retry-connrefused: is unknown
curl: try 'curl --help' or 'curl --manual' for more information
```

curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3

curl version 7.35.0 was released on January 29 2014 (when Remy was still at high school)

**Comment by peterbe** [comment]
Gross! So you'd have to upgrade curl before the tests can start?
Shall we go back to my [previous commit](https://github.com/mozilla-services/buildhub/pull/344/commits/3792aa5e202a096066d036df5323dc393fe403a9) which after all worked and solved the problem.

**Comment by peterbe** [comment]
Or, can we ditch Travis and just use Circle instead? Too soon?

**Comment by leplatrem** [comment]
> Shall we go back to my previous commit which after all worked and solved the problem.

Yes, whatever! I would personally prefer to have a couple of extra lines to upgrade curl on Travis than clutter the repo with extra folders and scripts, but I am absolutely not obtuse about that :)

> Or, can we ditch Travis and just use Circle instead? Too soon?

Yes of course you can!

**Pull request merged**
