### PR TITLE
Use with buildhub stage.

### PR DESCRIPTION
**Pull request by Natim**

### CODE REVIEW

**Comment by leplatrem** [comment]
Well, this is problematic if the bucket name is not the same one between servers....

**Comment by Natim** [comment]
> Well, this is problematic if the bucket name is not the same one between servers....

Why ? Can't it be part of the configuration?

**Comment by leplatrem** [comment]
> Why ? Can't it be part of the configuration?

It is a source of confusion, let's keep `buildhub` everywhere

**Comment by leplatrem** [comment]
The stage is slowly being populated in the right bucket. I believe we can merge/deploy this.

**Pull request merged**
